package com.adso.pos.model;


// The SaleItem class represents a single product with a specific quantity in a completed sale.
// It is a persistent data model that holds a snapshot of a product at the time of purchase.
public class SaleItem {
    private int id;
    private int saleId;
    private Product product;
    private int quantity;
    private double subtotal;

    // Constructor for creating a new SaleItem instance.
    // The id is not included as it will be generated by the database.
    public SaleItem(Product product, int quantity) {
        this.product = product;
        this.quantity = quantity;
        this.subtotal = product.getPrice() * quantity;
    }

    // Constructor for retrieving an existing SaleItem from the database.
    public SaleItem(int id, int saleId, Product product, int quantity, double subtotal) {
        this.id = id;
        this.saleId = saleId;
        this.product = product;
        this.quantity = quantity;
        this.subtotal = subtotal;
    }

    // Getters and Setters for the fields.
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getSaleId() {
        return saleId;
    }

    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }
}
